### ISSUE TITLE
Small bug: multiple submit clicks in "add new tokentype/transactiontag/membertype" creates duplicates

### ISSUE THREAD

**Issue by jssmk** [hacklab-fi/asylum#107]
Bug happens when you click submit button multiple times when creating a new token type, member type or transaction tag. Multiple submits create multiple instances.

Maybe requiring type names to be unique fixes this issue? Bug does not affect adding new access types, adding new members because of uniqueness requirement.

**Comment by jssmk** [comment]
(also affects sites/site and members/membernote)

**Comment by rambo** [comment]
I'm not sure there is any actual need for the labels to be unique, those that are too eager and create multiples can delete the extra ones manually.

**Comment by rambo** [comment]
Fixed in b3f8229
