### ISSUE TITLE
RecurringTransaction.in_timescope does not check the scope correctly

### ISSUE THREAD

**Issue by rambo** [hacklab-fi/asylum#119]

**Comment by jautero** [comment]
It would be nice to have some kind of repro instructions so that fixes could actually be tested.

**Comment by rambo** [comment]
True that, I just noticed this when creating some test data.
Basically the issue was that recurringtransactions that had ended were considered in-scope but it's not impossible I had some other problem elsewhere too, it was late...

I guess the check could be simplified to: `start <= scope_end and (not end or end >= scope_start)`
