### ISSUE TITLE
Add transport layer security

### ISSUE THREAD

**Issue by tanelikaivola** [hacklab-fi/asylum#14]
Move to https to make the connection secure (and maybe bundled/generate a self signed certificate for testing)

**Comment by rambo** [comment]
The production settings default to forcing redirect to https.

For a production Docker image use letsencrypt, the "buggy" nginx plugin worked just fine, but one needs to use the developer version of the CLI tool https://letsencrypt.readthedocs.org/en/latest/contributing.html#hacking

Also made a quick renewal script to be called monthly

    #!/bin/bash -e
    DOMAINS="-d hostname1.example.com -d hostname2.example.com"
    cd /opt/letsencrypt
    source venv/bin/activate
    letsencrypt -t --renew-by-default --agree-tos --redirect --nginx $DOMAINS
    etckeeper commit -m 'letsencrypt renewal'

**Comment by rambo** [comment]
Since production settings force https I'm closing this.
