### ISSUE TITLE
exporttokens-command exports external identifier without output escaping

### ISSUE THREAD

**Issue by tanelikaivola** [hacklab-fi/asylum#140]
#102 will introduce a new command that exports tokens as a sqlite3 database file

When access type contains external identifier with comma on it: "foo,bar" it will get exported to the valid_tokens table of the sqlite database as "value|10|foo,bar". Commas should be encoded somehow for  the sqlite database.

**Comment by rambo** [comment]
Maybe encode the list of external identifiers as JSON ?
