### ISSUE TITLE
As a secretary I want to have list of new applicants because they need to be accepted as members in board meeting.

### ISSUE THREAD

**Issue by jautero** [hacklab-fi/asylum#144]
There should be some way to list new applicants that have not been accepted as members.

**Comment by rambo** [comment]
Doesn't `/admin/members/membershipapplication/` cover this ? Applicants are handled separately from actual members anyway.

Having automatic applicant list "tag" for templates in #74 is a different issue IMO

**Comment by jautero** [comment]
What I meant is to have functionality similar to `./manage.py export_mailinglist --group=pending --format=name` in current implementation.

**Comment by rambo** [comment]
To copy-paste said info somewhere ? or what is the extended use-case here ? since all the info is available in the list, maybe just no in the most convinient format (the REST api gives you a nice JSON list as well for programming use).

**Comment by rambo** [comment]
In any case the secretary should not be running manage.py commands. There are multiple ways to get this info so closing.
