### ISSUE TITLE
Current build fails to build - scroll-reveal no longer found

### ISSUE THREAD

**Issue by tanelikaivola** [hacklab-fi/asylum#192]
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> npm WARN deprecated node-uuid@1.4.7: use uuid module instead
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

---

> bower scrollreveal#~2.3.2           ENOTFOUND Package scroll-reveal not found
> 
> npm ERR! Linux 4.4.47-boot2docker
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
> npm ERR! node v4.7.3
> npm ERR! npm  v2.15.11
> npm ERR! code ELIFECYCLE
> npm ERR! asylum@1.0.0 build: `npm i && bower install && gulp`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the asylum@1.0.0 build script 'npm i && bower install && gulp'.
> npm ERR! This is most likely a problem with the asylum package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     npm i && bower install && gulp
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs asylum
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!
> npm ERR!     npm owner ls asylum
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /opt/asylum/npm-debug.log

**Comment by rambo** [comment]
Should be fixed by 1135fcd
