### ISSUE TITLE
Member with scandic letters in name cannot apply

### ISSUE THREAD

**Issue by ojousima** [hacklab-fi/asylum#93]
If scandic letters "ÅÖÄåöä" Are entered to name field of application form, application displays error page 
```
UnicodeEncodeError at /members/apply

'ascii' codec can't encode character '\xc5' in position 81: ordinal not in range(128) 
.
.
.
Unicode error hint

The string that could not be encoded/decoded was: '> "Järvi,
```

**Comment by rambo** [comment]
Cannot reproduce on my dev env, maybe the docker image has some subtle misconfiguration ?

**Comment by jautero** [comment]
Neither on image built on Jenkins. Could you try to reproduce it with http://asylum.trollitehdas.fi/members/?

**Comment by ojousima** [comment]
I cannot reproduce the problem with http://asylum.trollitehdas.fi/members/. So maybe it is related to docker or something in setup of my system?

**Comment by jautero** [comment]
The reason is that it includes commit 3cea6d9d that implements on_saving that doesn't call print. (And therefore doesn't try to encode a string containing scandic letters.
